# Welcome to the sample config file
# Below you will find various config sections and options
# Default values are shown

# Options for connecting to the bot's Matrix account
matrix:
  # The Matrix User ID of the bot account
  user_id: ""
  # Matrix account password (optional if access token used)
  user_password: ""
  # Matrix account access token (optional if password used)
  #user_token: ""
  # The URL of the homeserver to connect to
  homeserver_url: https://matrix.org
  # The device ID that is **non pre-existing** device
  # You can choose any string as this value
  device_id:
  # What to name the logged in device
  device_name:

# Logging setup
logging:
  # Logging level
  # Allowed levels are 'INFO', 'WARNING', 'ERROR', 'DEBUG' where DEBUG is most verbose
  level: INFO
  # Configure logging to a file
  file_logging:
    # Whether logging to a file is enabled
    enabled: false
    # The path to the file to log to. May be relative or absolute
    filepath: bot.log
  # Configure logging to the console output
  console_logging:
    # Whether logging to the console is enabled
    enabled: true
